site_name: LMHXTS_blog
site_description: LMHXTSlearningnotes

theme:
  name: material
  language: zh # 设置为中文
  palette:
    scheme: slate
    primary: indigo
    accent: deep purple

nav:
  - 首页: index.md
  - 机器学习:
    - 贝叶斯学习: ml/Bayes.md
    - 决策树: ml/Decision_tree.md
    - K-近邻: ml/K-NN.md
    - CART: ml/Cart.md
    - XGBoost-数学推导: ml/Xgboost_math.md

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences # 支持高级代码块
  - pymdownx.details
  - attr_list
  - md_in_html

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.2.2/es5/tex-mml-chtml.js