site_name: LMHXTS Blog 
site_description: "Sich selber übervoll, sich selber bethauen, sich selber Regenguss sein einer verschmachtenden Wildniss." # 参考截图的副标题

theme:
  name: material
  language: zh # 设置为中文
  # 主题色彩与深浅色切换配置
  palette:
    # 方案 1：深色模式
    - scheme: slate
      primary: indigo            
      accent: deep purple       
      toggle:
        icon: material/weather-night
        name: 切换到浅色模式

    # 方案 2：浅色模式
    - scheme: default
      primary: white              
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: 切换到深色模式
  features:
    - navigation.tabs 
    - navigation.top  



# 核心：配置顶部 Tab 和左侧导航栏
nav:
  - HOME: index.md
  - 机器学习:           
      - 贝叶斯学习: ml/Bayes.md
      - 决策树: ml/Decision_tree.md
      - K-近邻: ml/K-NN.md
      - CART: ml/Cart.md
      - XGBoost数学推导: ml/Xgboost_math.md
      - 逻辑回归: ml/Logistic_Regression.md
  - 深度学习:           
      - BP神经网络: dl/BPNN.md
  - ABOUT: about.md


markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences 
  - pymdownx.details
  - attr_list
  - md_in_html

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.2.2/es5/tex-mml-chtml.js


plugins:
  - search
  - blog   